### ISSUE TITLE
Main thread exits before processing and abrupt termination?

### ISSUE THREAD

**Issue by fsauer65** [intenthq/wikidata-akka-streams#4]
Hi, very interesting article. I am trying your code and at first it doesn't do anything because the main thread exits before the flow gets a chance to do anything. When I add a Await.result(f, 20 minutes) at the end of the task method just before returning 0, it starts processing, but ends after 7.3 million records without printing anything (results or error message). Running it in the debugger confirms it never gets into the onComplete. I have a really hard time debugging this. Any thoughts?

Thanks,

Frank

**Comment by albertpastrana** [comment]
Thanks :-).
I'm not exactly sure what may be happening.
Have you done any changes in the code? In case you have, do you have any problem by executing a fresh clone of the repo?

**Comment by fsauer65** [comment]
It was caused by running it in/with IntelliJ. Running it with sbt works fine as expected... Thanks again for this great example of using Akka streams in its current form (I tinkered with it before but the api changed completely :-)
